// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateSDKKey = `-- name: AuthenticateSDKKey :one
SELECT environment FROM sdk_keys WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) AuthenticateSDKKey(ctx context.Context, keyHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, authenticateSDKKey, keyHash)
	var environment string
	err := row.Scan(&environment)
	return environment, err
}

const authenticateSession = `-- name: AuthenticateSession :one
SELECT u.id, u.handle, u.name, u.role, u.created_at, u.disabled_at
FROM sessions s
JOIN api_tokens t ON t.id = s.token_id
JOIN users u ON u.id = t.user_id
WHERE s.session_hash = $1
  AND s.expires_at > now()
  AND t.revoked_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > now())
  AND u.disabled_at IS NULL
`

// A session works only while its token and user are still active.
func (q *Queries) AuthenticateSession(ctx context.Context, sessionHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, authenticateSession, sessionHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const authenticateToken = `-- name: AuthenticateToken :one
SELECT u.id, u.handle, u.name, u.role, u.created_at, u.disabled_at, t.id AS token_id
FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
  AND t.revoked_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > now())
  AND u.disabled_at IS NULL
`

type AuthenticateTokenRow struct {
	ID         int64
	Handle     string
	Name       string
	Role       string
	CreatedAt  pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
	TokenID    int64
}

func (q *Queries) AuthenticateToken(ctx context.Context, tokenHash []byte) (AuthenticateTokenRow, error) {
	row := q.db.QueryRow(ctx, authenticateToken, tokenHash)
	var i AuthenticateTokenRow
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.TokenID,
	)
	return i, err
}

const createSDKKey = `-- name: CreateSDKKey :one
INSERT INTO sdk_keys (environment, name, key_hash, prefix)
VALUES ($1, $2, $3, $4)
RETURNING id, environment, name, key_hash, prefix, created_at, revoked_at
`

type CreateSDKKeyParams struct {
	Environment string
	Name        string
	KeyHash     []byte
	Prefix      string
}

func (q *Queries) CreateSDKKey(ctx context.Context, arg CreateSDKKeyParams) (SdkKey, error) {
	row := q.db.QueryRow(ctx, createSDKKey,
		arg.Environment,
		arg.Name,
		arg.KeyHash,
		arg.Prefix,
	)
	var i SdkKey
	err := row.Scan(
		&i.ID,
		&i.Environment,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_id, session_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenID     int64
	SessionHash []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenID, arg.SessionHash, arg.ExpiresAt)
	return err
}

const createToken = `-- name: CreateToken :one
INSERT INTO api_tokens (user_id, name, token_hash, prefix, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, prefix, created_at, expires_at, last_used_at, revoked_at
`

type CreateTokenParams struct {
	UserID    int64
	Name      string
	TokenHash []byte
	Prefix    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (handle, name, role)
VALUES ($1, $2, $3)
RETURNING id, handle, name, role, created_at, disabled_at
`

type CreateUserParams struct {
	Handle string
	Name   string
	Role   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Handle, arg.Name, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE session_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, sessionHash)
	return err
}

const disableUser = `-- name: DisableUser :exec
UPDATE users SET disabled_at = now() WHERE id = $1
`

func (q *Queries) DisableUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, handle, name, role, created_at, disabled_at FROM users WHERE handle = $1
`

func (q *Queries) GetUser(ctx context.Context, handle string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, handle, name, role, created_at, disabled_at FROM users WHERE handle = $1 FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, handle string) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const insertEnvironmentAuditEvent = `-- name: InsertEnvironmentAuditEvent :exec
INSERT INTO audit_events (actor, action, environment, before, after)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEnvironmentAuditEventParams struct {
	Actor       string
	Action      string
	Environment *string
	Before      []byte
	After       []byte
}

func (q *Queries) InsertEnvironmentAuditEvent(ctx context.Context, arg InsertEnvironmentAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertEnvironmentAuditEvent,
		arg.Actor,
		arg.Action,
		arg.Environment,
		arg.Before,
		arg.After,
	)
	return err
}

const insertUserAuditEvent = `-- name: InsertUserAuditEvent :exec
INSERT INTO audit_events (actor, action, subject_user, before, after)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserAuditEventParams struct {
	Actor       string
	Action      string
	SubjectUser *string
	Before      []byte
	After       []byte
}

func (q *Queries) InsertUserAuditEvent(ctx context.Context, arg InsertUserAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertUserAuditEvent,
		arg.Actor,
		arg.Action,
		arg.SubjectUser,
		arg.Before,
		arg.After,
	)
	return err
}

const listEnvironmentAuditEvents = `-- name: ListEnvironmentAuditEvents :many
SELECT id, occurred_at, actor, action, flag_key, environment, before, after, subject_user FROM audit_events
WHERE environment = $1 AND flag_key IS NULL
ORDER BY id
`

func (q *Queries) ListEnvironmentAuditEvents(ctx context.Context, environment *string) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listEnvironmentAuditEvents, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.FlagKey,
			&i.Environment,
			&i.Before,
			&i.After,
			&i.SubjectUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSDKKeys = `-- name: ListSDKKeys :many
SELECT id, environment, name, key_hash, prefix, created_at, revoked_at FROM sdk_keys ORDER BY environment, id
`

func (q *Queries) ListSDKKeys(ctx context.Context) ([]SdkKey, error) {
	rows, err := q.db.Query(ctx, listSDKKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SdkKey
	for rows.Next() {
		var i SdkKey
		if err := rows.Scan(
			&i.ID,
			&i.Environment,
			&i.Name,
			&i.KeyHash,
			&i.Prefix,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokens = `-- name: ListTokens :many
SELECT id, user_id, name, token_hash, prefix, created_at, expires_at, last_used_at, revoked_at FROM api_tokens WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListTokens(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAuditEvents = `-- name: ListUserAuditEvents :many
SELECT id, occurred_at, actor, action, flag_key, environment, before, after, subject_user FROM audit_events WHERE subject_user = $1 ORDER BY id
`

func (q *Queries) ListUserAuditEvents(ctx context.Context, subjectUser *string) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listUserAuditEvents, subjectUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.FlagKey,
			&i.Environment,
			&i.Before,
			&i.After,
			&i.SubjectUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, handle, name, role, created_at, disabled_at FROM users ORDER BY handle
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSDKKey = `-- name: RevokeSDKKey :one
UPDATE sdk_keys SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, environment, name, key_hash, prefix, created_at, revoked_at
`

func (q *Queries) RevokeSDKKey(ctx context.Context, id int64) (SdkKey, error) {
	row := q.db.QueryRow(ctx, revokeSDKKey, id)
	var i SdkKey
	err := row.Scan(
		&i.ID,
		&i.Environment,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :one
UPDATE api_tokens SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, user_id, name, token_hash, prefix, created_at, expires_at, last_used_at, revoked_at
`

type RevokeTokenParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, revokeToken, arg.ID, arg.UserID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeUserTokens = `-- name: RevokeUserTokens :exec
UPDATE api_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeUserTokens, userID)
	return err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $2 WHERE id = $1 RETURNING id, handle, name, role, created_at, disabled_at
`

type SetUserRoleParams struct {
	ID   int64
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const touchToken = `-- name: TouchToken :exec
UPDATE api_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

// Throttled so authentication isn't a write on every request.
func (q *Queries) TouchToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchToken, id)
	return err
}
