// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_queries.sql

package db

import (
	"context"
)

const beginIdempotencyKey = `-- name: BeginIdempotencyKey :one
INSERT INTO idempotency_keys (user_handle, key, request_hash)
VALUES ($1, $2, $3)
ON CONFLICT (user_handle, key) DO UPDATE
SET request_hash = EXCLUDED.request_hash, status = NULL, headers = NULL, body = NULL, created_at = now()
WHERE idempotency_keys.created_at < now() - make_interval(secs => $4::float8)
   OR (idempotency_keys.status IS NULL
       AND idempotency_keys.created_at < now() - make_interval(secs => $5::float8))
RETURNING user_handle
`

type BeginIdempotencyKeyParams struct {
	UserHandle  string
	Key         string
	RequestHash []byte
	TtlSecs     float64
	StaleSecs   float64
}

// Returns a row only if the key was free (new, expired, or abandoned).
func (q *Queries) BeginIdempotencyKey(ctx context.Context, arg BeginIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, beginIdempotencyKey,
		arg.UserHandle,
		arg.Key,
		arg.RequestHash,
		arg.TtlSecs,
		arg.StaleSecs,
	)
	var user_handle string
	err := row.Scan(&user_handle)
	return user_handle, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys SET status = $3, headers = $4, body = $5
WHERE user_handle = $1 AND key = $2
`

type CompleteIdempotencyKeyParams struct {
	UserHandle string
	Key        string
	Status     *int32
	Headers    []byte
	Body       []byte
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.UserHandle,
		arg.Key,
		arg.Status,
		arg.Headers,
		arg.Body,
	)
	return err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys
WHERE created_at < now() - make_interval(secs => $1::float8)
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, ttlSecs float64) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, ttlSecs)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT user_handle, key, request_hash, status, headers, body, created_at FROM idempotency_keys WHERE user_handle = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	UserHandle string
	Key        string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserHandle, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserHandle,
		&i.Key,
		&i.RequestHash,
		&i.Status,
		&i.Headers,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE user_handle = $1 AND key = $2 AND status IS NULL
`

type ReleaseIdempotencyKeyParams struct {
	UserHandle string
	Key        string
}

func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.UserHandle, arg.Key)
	return err
}
