// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID          int64
	OccurredAt  pgtype.Timestamptz
	Actor       string
	Action      string
	FlagKey     *string
	Environment *string
	Before      []byte
	After       []byte
}

type Environment struct {
	Key       string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Flag struct {
	ID          int64
	Key         string
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
}

type FlagEnvironment struct {
	FlagID            int64
	Environment       string
	Enabled           bool
	RolloutPercentage int16
	Rules             []byte
	UpdatedAt         pgtype.Timestamptz
}
