// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         int64
	UserID     int64
	Name       string
	TokenHash  []byte
	Prefix     string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type AuditEvent struct {
	ID          int64
	OccurredAt  pgtype.Timestamptz
	Actor       string
	Action      string
	FlagKey     *string
	Environment *string
	Before      []byte
	After       []byte
	SubjectUser *string
}

type Environment struct {
	Key       string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Flag struct {
	ID          int64
	Key         string
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
}

type FlagEnvironment struct {
	FlagID            int64
	Environment       string
	Enabled           bool
	RolloutPercentage int16
	Rules             []byte
	UpdatedAt         pgtype.Timestamptz
}

type SdkKey struct {
	ID          int64
	Environment string
	Name        string
	KeyHash     []byte
	Prefix      string
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type User struct {
	ID         int64
	Handle     string
	Name       string
	Role       string
	CreatedAt  pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
}
