// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const archiveFlag = `-- name: ArchiveFlag :exec
UPDATE flags SET archived_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) ArchiveFlag(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, archiveFlag, id)
	return err
}

const backfillFlagEnvironments = `-- name: BackfillFlagEnvironments :exec
INSERT INTO flag_environments (flag_id, environment)
SELECT id, $1 FROM flags
`

// Gives every existing flag (archived too) default settings in a new environment.
func (q *Queries) BackfillFlagEnvironments(ctx context.Context, environment string) error {
	_, err := q.db.Exec(ctx, backfillFlagEnvironments, environment)
	return err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (key, name, protected)
VALUES ($1, $2, $3)
RETURNING key, name, created_at, protected
`

type CreateEnvironmentParams struct {
	Key       string
	Name      string
	Protected bool
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.Key, arg.Name, arg.Protected)
	var i Environment
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.Protected,
	)
	return i, err
}

const createFlag = `-- name: CreateFlag :one
INSERT INTO flags (key, name, description)
VALUES ($1, $2, $3)
RETURNING id, key, name, description, created_at, updated_at, archived_at
`

type CreateFlagParams struct {
	Key         string
	Name        string
	Description string
}

func (q *Queries) CreateFlag(ctx context.Context, arg CreateFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, createFlag, arg.Key, arg.Name, arg.Description)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createFlagEnvironments = `-- name: CreateFlagEnvironments :exec
INSERT INTO flag_environments (flag_id, environment)
SELECT $1, key FROM environments
`

func (q *Queries) CreateFlagEnvironments(ctx context.Context, flagID int64) error {
	_, err := q.db.Exec(ctx, createFlagEnvironments, flagID)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT key, name, created_at, protected FROM environments WHERE key = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, key string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, key)
	var i Environment
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.Protected,
	)
	return i, err
}

const getEnvironmentForUpdate = `-- name: GetEnvironmentForUpdate :one
SELECT key, name, created_at, protected FROM environments WHERE key = $1 FOR UPDATE
`

func (q *Queries) GetEnvironmentForUpdate(ctx context.Context, key string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentForUpdate, key)
	var i Environment
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.Protected,
	)
	return i, err
}

const getEvalConfig = `-- name: GetEvalConfig :one
SELECT fe.enabled, fe.rollout_percentage, fe.rules
FROM flags f
JOIN flag_environments fe ON fe.flag_id = f.id
WHERE f.key = $1 AND fe.environment = $2 AND f.archived_at IS NULL
`

type GetEvalConfigParams struct {
	Key         string
	Environment string
}

type GetEvalConfigRow struct {
	Enabled           bool
	RolloutPercentage int16
	Rules             []byte
}

func (q *Queries) GetEvalConfig(ctx context.Context, arg GetEvalConfigParams) (GetEvalConfigRow, error) {
	row := q.db.QueryRow(ctx, getEvalConfig, arg.Key, arg.Environment)
	var i GetEvalConfigRow
	err := row.Scan(&i.Enabled, &i.RolloutPercentage, &i.Rules)
	return i, err
}

const getFlag = `-- name: GetFlag :one
SELECT id, key, name, description, created_at, updated_at, archived_at FROM flags WHERE key = $1
`

func (q *Queries) GetFlag(ctx context.Context, key string) (Flag, error) {
	row := q.db.QueryRow(ctx, getFlag, key)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getFlagEnvironmentForUpdate = `-- name: GetFlagEnvironmentForUpdate :one
SELECT flag_id, environment, enabled, rollout_percentage, rules, updated_at FROM flag_environments
WHERE flag_id = $1 AND environment = $2
FOR UPDATE
`

type GetFlagEnvironmentForUpdateParams struct {
	FlagID      int64
	Environment string
}

func (q *Queries) GetFlagEnvironmentForUpdate(ctx context.Context, arg GetFlagEnvironmentForUpdateParams) (FlagEnvironment, error) {
	row := q.db.QueryRow(ctx, getFlagEnvironmentForUpdate, arg.FlagID, arg.Environment)
	var i FlagEnvironment
	err := row.Scan(
		&i.FlagID,
		&i.Environment,
		&i.Enabled,
		&i.RolloutPercentage,
		&i.Rules,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlagForUpdate = `-- name: GetFlagForUpdate :one
SELECT id, key, name, description, created_at, updated_at, archived_at FROM flags WHERE key = $1 FOR UPDATE
`

func (q *Queries) GetFlagForUpdate(ctx context.Context, key string) (Flag, error) {
	row := q.db.QueryRow(ctx, getFlagForUpdate, key)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (actor, action, flag_key, environment, before, after)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditEventParams struct {
	Actor       string
	Action      string
	FlagKey     *string
	Environment *string
	Before      []byte
	After       []byte
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.Actor,
		arg.Action,
		arg.FlagKey,
		arg.Environment,
		arg.Before,
		arg.After,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, occurred_at, actor, action, flag_key, environment, before, after, subject_user FROM audit_events WHERE flag_key = $1 ORDER BY id
`

func (q *Queries) ListAuditEvents(ctx context.Context, flagKey *string) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, flagKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.FlagKey,
			&i.Environment,
			&i.Before,
			&i.After,
			&i.SubjectUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT key, name, created_at, protected FROM environments ORDER BY key
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.CreatedAt,
			&i.Protected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlagEnvironments = `-- name: ListFlagEnvironments :many
SELECT flag_id, environment, enabled, rollout_percentage, rules, updated_at FROM flag_environments WHERE flag_id = ANY($1::bigint[])
`

func (q *Queries) ListFlagEnvironments(ctx context.Context, flagIds []int64) ([]FlagEnvironment, error) {
	rows, err := q.db.Query(ctx, listFlagEnvironments, flagIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlagEnvironment
	for rows.Next() {
		var i FlagEnvironment
		if err := rows.Scan(
			&i.FlagID,
			&i.Environment,
			&i.Enabled,
			&i.RolloutPercentage,
			&i.Rules,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlags = `-- name: ListFlags :many
SELECT id, key, name, description, created_at, updated_at, archived_at FROM flags WHERE archived_at IS NULL ORDER BY key
`

func (q *Queries) ListFlags(ctx context.Context) ([]Flag, error) {
	rows, err := q.db.Query(ctx, listFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchFlag = `-- name: TouchFlag :exec
UPDATE flags SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchFlag(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchFlag, id)
	return err
}

const updateEnvironmentSettings = `-- name: UpdateEnvironmentSettings :one
UPDATE environments SET name = $2, protected = $3
WHERE key = $1
RETURNING key, name, created_at, protected
`

type UpdateEnvironmentSettingsParams struct {
	Key       string
	Name      string
	Protected bool
}

func (q *Queries) UpdateEnvironmentSettings(ctx context.Context, arg UpdateEnvironmentSettingsParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentSettings, arg.Key, arg.Name, arg.Protected)
	var i Environment
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.CreatedAt,
		&i.Protected,
	)
	return i, err
}

const updateFlag = `-- name: UpdateFlag :one
UPDATE flags SET name = $2, description = $3, updated_at = now()
WHERE id = $1
RETURNING id, key, name, description, created_at, updated_at, archived_at
`

type UpdateFlagParams struct {
	ID          int64
	Name        string
	Description string
}

func (q *Queries) UpdateFlag(ctx context.Context, arg UpdateFlagParams) (Flag, error) {
	row := q.db.QueryRow(ctx, updateFlag, arg.ID, arg.Name, arg.Description)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateFlagEnvironment = `-- name: UpdateFlagEnvironment :exec
UPDATE flag_environments
SET enabled = $3, rollout_percentage = $4, rules = $5, updated_at = now()
WHERE flag_id = $1 AND environment = $2
`

type UpdateFlagEnvironmentParams struct {
	FlagID            int64
	Environment       string
	Enabled           bool
	RolloutPercentage int16
	Rules             []byte
}

func (q *Queries) UpdateFlagEnvironment(ctx context.Context, arg UpdateFlagEnvironmentParams) error {
	_, err := q.db.Exec(ctx, updateFlagEnvironment,
		arg.FlagID,
		arg.Environment,
		arg.Enabled,
		arg.RolloutPercentage,
		arg.Rules,
	)
	return err
}
