// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expireChangeRequests = `-- name: ExpireChangeRequests :many
WITH expired AS (
    UPDATE change_requests cr
    SET status = 'expired', resolved_at = now()
    WHERE cr.status = 'pending' AND cr.expires_at <= now()
      AND ($1::bigint IS NULL OR cr.flag_id = $1)
      AND ($2::text IS NULL OR cr.environment = $2)
    RETURNING cr.id, cr.flag_id, cr.environment, cr.requested_by, cr.reason, cr.base, cr.proposed, cr.status, cr.reviewed_by, cr.review_comment, cr.created_at, cr.expires_at, cr.resolved_at
)
SELECT e.id, e.requested_by, e.reason, e.proposed, e.environment, f.key AS flag_key
FROM expired e JOIN flags f ON f.id = e.flag_id
ORDER BY e.id
`

type ExpireChangeRequestsParams struct {
	FlagID      *int64
	Environment *string
}

type ExpireChangeRequestsRow struct {
	ID          int64
	RequestedBy string
	Reason      string
	Proposed    []byte
	Environment string
	FlagKey     string
}

// Expires pending requests past their expiry, optionally for one flag and
// environment, and returns them for auditing.
func (q *Queries) ExpireChangeRequests(ctx context.Context, arg ExpireChangeRequestsParams) ([]ExpireChangeRequestsRow, error) {
	rows, err := q.db.Query(ctx, expireChangeRequests, arg.FlagID, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpireChangeRequestsRow
	for rows.Next() {
		var i ExpireChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestedBy,
			&i.Reason,
			&i.Proposed,
			&i.Environment,
			&i.FlagKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChangeRequest = `-- name: GetChangeRequest :one
SELECT cr.id, cr.flag_id, cr.environment, cr.requested_by, cr.reason, cr.base, cr.proposed, cr.status, cr.reviewed_by, cr.review_comment, cr.created_at, cr.expires_at, cr.resolved_at, f.key AS flag_key
FROM change_requests cr JOIN flags f ON f.id = cr.flag_id
WHERE cr.id = $1
`

type GetChangeRequestRow struct {
	ID            int64
	FlagID        int64
	Environment   string
	RequestedBy   string
	Reason        string
	Base          []byte
	Proposed      []byte
	Status        string
	ReviewedBy    *string
	ReviewComment string
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	FlagKey       string
}

func (q *Queries) GetChangeRequest(ctx context.Context, id int64) (GetChangeRequestRow, error) {
	row := q.db.QueryRow(ctx, getChangeRequest, id)
	var i GetChangeRequestRow
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.Environment,
		&i.RequestedBy,
		&i.Reason,
		&i.Base,
		&i.Proposed,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewComment,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.FlagKey,
	)
	return i, err
}

const getChangeRequestForUpdate = `-- name: GetChangeRequestForUpdate :one
SELECT cr.id, cr.flag_id, cr.environment, cr.requested_by, cr.reason, cr.base, cr.proposed, cr.status, cr.reviewed_by, cr.review_comment, cr.created_at, cr.expires_at, cr.resolved_at, f.key AS flag_key
FROM change_requests cr JOIN flags f ON f.id = cr.flag_id
WHERE cr.id = $1
FOR UPDATE OF cr
`

type GetChangeRequestForUpdateRow struct {
	ID            int64
	FlagID        int64
	Environment   string
	RequestedBy   string
	Reason        string
	Base          []byte
	Proposed      []byte
	Status        string
	ReviewedBy    *string
	ReviewComment string
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	FlagKey       string
}

func (q *Queries) GetChangeRequestForUpdate(ctx context.Context, id int64) (GetChangeRequestForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getChangeRequestForUpdate, id)
	var i GetChangeRequestForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.Environment,
		&i.RequestedBy,
		&i.Reason,
		&i.Base,
		&i.Proposed,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewComment,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.FlagKey,
	)
	return i, err
}

const insertChangeRequest = `-- name: InsertChangeRequest :one
INSERT INTO change_requests (flag_id, environment, requested_by, reason, base, proposed, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertChangeRequestParams struct {
	FlagID      int64
	Environment string
	RequestedBy string
	Reason      string
	Base        []byte
	Proposed    []byte
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertChangeRequest(ctx context.Context, arg InsertChangeRequestParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChangeRequest,
		arg.FlagID,
		arg.Environment,
		arg.RequestedBy,
		arg.Reason,
		arg.Base,
		arg.Proposed,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listChangeRequests = `-- name: ListChangeRequests :many
SELECT cr.id, cr.flag_id, cr.environment, cr.requested_by, cr.reason, cr.base, cr.proposed, cr.status, cr.reviewed_by, cr.review_comment, cr.created_at, cr.expires_at, cr.resolved_at, f.key AS flag_key
FROM change_requests cr JOIN flags f ON f.id = cr.flag_id
WHERE ($1::text IS NULL OR cr.status = $1)
  AND ($2::text IS NULL OR f.key = $2)
ORDER BY cr.id DESC
LIMIT 500
`

type ListChangeRequestsParams struct {
	Status  *string
	FlagKey *string
}

type ListChangeRequestsRow struct {
	ID            int64
	FlagID        int64
	Environment   string
	RequestedBy   string
	Reason        string
	Base          []byte
	Proposed      []byte
	Status        string
	ReviewedBy    *string
	ReviewComment string
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	FlagKey       string
}

func (q *Queries) ListChangeRequests(ctx context.Context, arg ListChangeRequestsParams) ([]ListChangeRequestsRow, error) {
	rows, err := q.db.Query(ctx, listChangeRequests, arg.Status, arg.FlagKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangeRequestsRow
	for rows.Next() {
		var i ListChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.FlagID,
			&i.Environment,
			&i.RequestedBy,
			&i.Reason,
			&i.Base,
			&i.Proposed,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewComment,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ResolvedAt,
			&i.FlagKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveChangeRequest = `-- name: ResolveChangeRequest :execrows
UPDATE change_requests
SET status = $2, reviewed_by = $3, review_comment = $4, resolved_at = now()
WHERE id = $1 AND status = 'pending'
`

type ResolveChangeRequestParams struct {
	ID            int64
	Status        string
	ReviewedBy    *string
	ReviewComment string
}

func (q *Queries) ResolveChangeRequest(ctx context.Context, arg ResolveChangeRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveChangeRequest,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewComment,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
